name: Code Lint

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Container
        run: docker-compose up -d --build

      - name: Down Container
        run: docker-compose down
