name: Unit Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start Container
        run: docker-compose up -d --build

      - name: Install dependencies
        run: docker-compose exec -T action composer install

      - name: Run PHPUnit Tests
        run: docker-compose exec -T action composer test

      - name: Down Container
        run: docker-compose down
